### PR TITLE
WIP: Change logos to pyjamas logos

### PR DESCRIPTION
**Pull request by alexandrebarbaruiva**
Steps to finish changing

- [ ] Update images on `img/sprite`
- [X] Update organizers' images on `img/organizers`
- [X] Update `apple-touch-icon` images on `img/favicons`
- [ ] Update `favicon` images on `img/favicons`

### CODE REVIEW

**Comment by Cheukting** [comment]
@camilamaia do you have a logo in the svg format so we can finish this PR?

**Comment by camilamaia** [comment]
I don't have it. But I tried to convert the png one to svg. The only thing is that the result is black and white https://drive.google.com/file/d/162616CXMIZ2kHOvNSn8iQJomXFRVsTg2/view?usp=sharing

**Comment by camilamaia** [comment]
@Cheukting here: https://drive.google.com/drive/u/1/folders/1wZDL10Ls7VZ7C3y8bnhX_NJu8NHOXk0k

I asked in the old pyjamas group and they have it 😊

**Comment by Cheukting** [comment]
> @Cheukting here: https://drive.google.com/drive/u/1/folders/1wZDL10Ls7VZ7C3y8bnhX_NJu8NHOXk0k
> 
> I asked in the old pyjamas group and they have it 😊

Amazing! @alexandrebarbaruiva do you want to finish this PR soon-ish? I want to promo in EuroPython next week so really want it to be done this weekend. If you are busy we will just merge this and I will take care of the rest.

**Comment by alexandrebarbaruiva** [comment]
@Cheukting I can't guarantee this weekend, maybe tomorrow or tuesday

**Comment by Cheukting** [comment]
> @Cheukting I can't guarantee this weekend, maybe tomorrow or tuesday

thanks, @alexandrebarbaruiva I have time tomorrow night (Tuesday) so if you cannot do it I will take over. :-)

**Pull request merged**
